// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Process from "process";
import * as Buntest from "bun:test";
import * as Nodepath from "node:path";
import * as Principium from "./Principium.js";

let repo = Nodepath.resolve(import.meta.dir, "../repos/deno/single-project");

Buntest.describe("A single ReScript project using deno as package manager", () => {
  let orginalCwd = Process.cwd();
  Buntest.beforeAll(async () => await Principium.changeCwdToRepository(repo, async () => {
    await $$Bun.$`deno install`;
  }));
  Buntest.afterAll(async () => {
    Process.chdir(orginalCwd);
  });
  Buntest.test("should clean", async () => {
    await $$Bun.$`deno task clean`;
  });
  Buntest.test("should build", async () => {
    await $$Bun.$`deno task build`;
  });
});

export {
  repo,
}
/* repo Not a pure module */
