// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Process from "process";
import * as Buntest from "bun:test";
import * as Nodepath from "node:path";

let repo = Nodepath.resolve(import.meta.dir, "../repos/npm/single-project");

Buntest.describe("A single ReScript project using npm as package manager", () => {
  let orginalCwd = Process.cwd();
  Buntest.beforeAll(async () => {
    Process.chdir(repo);
    await $$Bun.$`npm install`;
    let match = Process.env;
    if (match.CI !== "true") {
      return;
    }
    console.log("This test is running in CI");
  });
  Buntest.afterAll(async () => {
    Process.chdir(orginalCwd);
  });
  Buntest.test("should always pass", async () => {
    console.log(repo);
  });
  Buntest.test("should clean", async () => {
    await $$Bun.$`npx rescript clean`;
  });
  Buntest.test("should build", async () => {
    await $$Bun.$`npx rescript build`;
  });
});

export {
  repo,
}
/* repo Not a pure module */
