// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Bun from "bun";
import * as Process from "process";
import * as Buntest from "bun:test";
import * as Nodepath from "node:path";
import * as Principium from "./Principium.js";

let repo = Nodepath.resolve(import.meta.dir, "../repos/pnpm/monorepo");

Buntest.describe("A monorepo ReScript project using pnpm as package manager", () => {
  let orginalCwd = Process.cwd();
  Buntest.beforeAll(async () => await Principium.changeCwdToRepository(repo, async () => {
    await $$Bun.$`pnpm install`;
  }));
  Buntest.afterAll(async () => {
    Process.chdir(orginalCwd);
  });
  Buntest.test("should clean", async () => {
    await $$Bun.$`pnpm run clean`;
  });
  Buntest.test("should build", async () => {
    await $$Bun.$`pnpm run build`;
  });
  Buntest.test("should clean/build individual project", async () => {
    let packageAPath = Nodepath.resolve(repo, "packages", "a");
    await $$Bun.$`npx rescript clean`.cwd(packageAPath);
    await $$Bun.$`npx rescript build`.cwd(packageAPath);
  });
});

export {
  repo,
}
/* repo Not a pure module */
