name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - run: corepack enable
      - run: bun install
      - run: bun run test

  notify:
    runs-on: ubuntu-latest
    needs: main
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    steps:
      - uses: lacherogwu/failed-jobs-discord-notification-action@v1
        with:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          needs_json: ${{ toJSON(needs) }}
